import Template1 from "../components/featured/resumeTemplates/Template1";
import Template2 from "../components/featured/resumeTemplates/Template2";

export const companyLogo = [
  {
    img: "/images/home/scroller-img_1.png",
  },
];
export const jobCatData = [
  {
    img: "/images/home/finance.png",
    name: "Finance",
    job: "1598 jobs",
  },
  {
    img: "/images/home/Marketing.png",
    name: "Marketing",
    job: "1598 jobs",
  },
  {
    img: "/images/home/HR.png",
    name: "Human Resources",
    job: "1598 jobs",
  },
  {
    img: "/images/home/industry.png",
    name: "Industry",
    job: "1598 jobs",
  },
  {
    img: "/images/home/Design & cr.png",
    name: "Design & Creative",
    job: "1598 jobs",
  },
  {
    img: "/images/home/Content_writer.png",
    name: "Content Writing",
    job: "1598 jobs",
  },
  {
    img: "/images/home/Development.png",
    name: "Development & IT",
    job: "1598 jobs",
  },
  {
    img: "/images/home/Video editing.png",
    name: "Video Editing",
    job: "1598 jobs",
  },
  {
    img: "/images/home/Project management.png",
    name: "Project Management",
    job: "1598 jobs",
  },
  {
    img: "/images/home/accounts.png",
    name: "Accounts",
    job: "1598 jobs",
  },
  {
    img: "/images/home/organization.png",
    name: "Organization",
    job: "1598 jobs",
  },
  {
    img: "/images/home/networking.png",
    name: "Networking",
    job: "1598 jobs",
  },
];

export const SkillList = [
  "JavaScript",
  "Java",
  "Python",
  "C#",
  "C++",
  "Ruby",
  "Swift",
  "Objective-C",
  "PHP",
  "HTML",
  "CSS",
  "React",
  "Angular",
  "Vue.js",
  "Node.js",
  "plumber",
  "Express.js",
  "Django",
  "Flask",
  "Spring",
  "Ruby on Rails",
  "ASP.NET",
  "MySQL",
  "PostgreSQL",
  "MongoDB",
  "SQL Server",
  "Git",
  "GitHub",
  "GitLab",
  "Jira",
  "Confluence",
  "AWS",
  "Azure",
  "Google Cloud Platform",
  "Docker",
  "Kubernetes",
  "Linux",
  "Windows",
  "iOS",
  "Android",
  "RESTful APIs",
  "GraphQL",
  "Redux",
  "VueX",
  "Webpack",
  "Jenkins",
  "Travis CI",
  "Agile",
  "Scrum",
  "Kanban",
  "UX/UI Design",
  "Photoshop",
  "Sketch",
  "Figma",
  "Adobe XD",
  "Wireframing",
  "Prototyping",
  "Machine Learning",
  "Data Science",
  "TensorFlow",
  "PyTorch",
  "NLP (Natural Language Processing)",
  "Blockchain",
  "Smart Contracts",
  "Cybersecurity",
  "Penetration Testing",
  "Network Administration",
  "DevOps",
  "Site Reliability Engineering (SRE)",
  "QA Testing",
  "Selenium",
  "JIRA",
  "Postman",
  "REST Assured",
  "Communication Skills",
  "Problem Solving",
  "Critical Thinking",
  "Time Management",
  "Adaptability",
  "Creativity",
  "Leadership",
  "Teamwork",
  "Project Management",
  "Customer Service",
  "Sales",
  "Marketing",
  "Negotiation",
  "Financial Analysis",
  "Data Analysis",
  "Research",
  "Public Speaking",
  "Event Planning",
  "Writing",
  "Editing",
  "Multilingualism",
  "Translation",
  "Teaching",
  "Training",
  "Mentoring",
  "Coaching",
  "Human Resources",
  "Recruitment",
  "Employee Relations",
  "Conflict Resolution",
  "Health and Safety",
  "Quality Control",
  "Manufacturing",
  "Supply Chain Management",
  "Logistics",
  "Retail",
  "Hospitality",
  "Culinary Arts",
  "Graphic Design",
  "Video Production",
  "Photography",
  "Fashion Design",
  "Interior Design",
  "Architecture",
  "Civil Engineering",
  "Mechanical Engineering",
  "Electrical Engineering",
  "Chemical Engineering",
  "Biotechnology",
  "Environmental Science",
  "Meteorology",
  "Agriculture",
  "Forestry",
  "Veterinary Medicine",
  "Pharmacy",
  "Nursing",
  "Medicine",
  "Dentistry",
  "Physical Therapy",
  "Psychology",
  "Social Work",
  "Counseling",
  "Law",
  "Legal Research",
  "Paralegal",
  "Investment Banking",
  "Financial Planning",
  "Actuarial Science",
  "Real Estate",
  "Insurance",
  "Information Security",
  "System Administration",
  "Artificial Intelligence",
  "Virtual Reality",
  "Augmented Reality",
  "Robotics",
  "Biomedical Engineering",
  "Renewable Energy",
  "Astronomy",
  "Space Exploration",
  "Geology",
  "Paleontology",
  "Anthropology",
  "Sociology",
  "Political Science",
  "Economics",
  "International Relations",
  "History",
  "Archaeology",
  "Philosophy",
  "Religious Studies",
  "Linguistics",
  "Literature",
  "Music",
  "Performing Arts",
  "Sports",
  "Fitness Training",
  "Yoga Instruction",
  "Dance",
  "Gaming",
  "Programming",
  "Database Administration",
  "Web Development",
  "Mobile App Development",
  "UI/UX Design",
  "Cloud Computing",
  "Quality Assurance",
  "Technical Writing",
  "Editing and Publishing",
  "Content Creation",
  "SEO (Search Engine Optimization)",
  "Digital Marketing",
  "Social Media Management",
  "E-commerce",
  "Data Entry",
  "Administrative Support",
  "Virtual Assistance",
  "Education",
  "Research and Development",
  "Public Relations",
  "Nonprofit Management",
  "Fundraising",
  "Event Management",
  "Tourism",
  "Healthcare Administration",
  "Pharmaceuticals",
  "Biomedical Research",
  "Chemical Research",
  "Environmental Research",
  "Market Research",
  "Laboratory Techniques",
  "Manufacturing Operations",
  "Supply Chain",
  "Logistics Management",
  "Retail Management",
  "Customer Relationship Management",
  "Hospitality Management",
  "Restaurant Management",
  "Public Health",
  "Epidemiology",
  "Nutrition",
  "Fitness Instruction",
  "Social Media Marketing",
  "Content Strategy",
  "Brand Management",
  "Digital Advertising",
  "Market Analysis",
  "Salesforce Administration",
  "Data Warehousing",
  "Business Analysis",
  "Customer Relationship Management (CRM)",
  "Risk Management",
  "Financial Planning and Analysis (FP&A)",
  "Taxation",
  "Audit and Compliance",
  "Contract Management",
  "Legal Writing",
  "Intellectual Property Law",
  "Corporate Law",
  "Labor Law",
  "Family Law",
  "International Law",
  "Patent Law",
  "Legal Research and Writing",
  "Mental Health Counseling",
  "School Counseling",
  "Career Counseling",
  "Social Services",
  "Public Administration",
  "Government Affairs",
  "Public Policy",
  "Political Campaigning",
  "Foreign Policy",
  "Diplomacy",
  "International Development",
  "Interpreting",
  "Language Teaching",
  "Curriculum Development",
  "Educational Technology",
  "Online Teaching",
  "Adult Education",
  "Corporate Training",
  "Technical Training",
  "Instructional Design",
  "Learning and Development",
  "Employee Training",
  "Safety Training",
  "Operations Management",
  "Process Improvement",
  "Six Sigma",
  "Lean Manufacturing",
  "Supply Chain Optimization",
  "Inventory Management",
  "Retail Merchandising",
  "Visual Merchandising",
  "Store Management",
  "Retail Buying",
  "E-commerce Management",
  "Textile Design",
  "Merchandising",
  "Pattern Making",
  "Technical Drawing",
  "Sustainable Fashion",
  "Space Planning",
  "Furniture Design",
  "3D Rendering",
  "Architectural Design",
  "Building Information Modeling (BIM)",
  "Urban Planning",
  "Landscape Architecture",
  "Construction Management",
  "Structural Engineering",
  "Geotechnical Engineering",
  "Environmental Engineering",
  "Materials Science",
  "Renewable",
  "Wind Energy",
  "Solar Energy",
  "Astrophysics",
];

export const telCode = [
  {
    name: "Afghanistan",
    flag: "🇦🇫",
    code: "AF",
    dial_code: "+93",
  },
  {
    name: "Åland Islands",
    flag: "🇦🇽",
    code: "AX",
    dial_code: "+358",
  },
  {
    name: "Albania",
    flag: "🇦🇱",
    code: "AL",
    dial_code: "+355",
  },
  {
    name: "Algeria",
    flag: "🇩🇿",
    code: "DZ",
    dial_code: "+213",
  },
  {
    name: "American Samoa",
    flag: "🇦🇸",
    code: "AS",
    dial_code: "+1684",
  },
  {
    name: "Andorra",
    flag: "🇦🇩",
    code: "AD",
    dial_code: "+376",
  },
  {
    name: "Angola",
    flag: "🇦🇴",
    code: "AO",
    dial_code: "+244",
  },
  {
    name: "Anguilla",
    flag: "🇦🇮",
    code: "AI",
    dial_code: "+1264",
  },
  {
    name: "Antarctica",
    flag: "🇦🇶",
    code: "AQ",
    dial_code: "+672",
  },
  {
    name: "Antigua and Barbuda",
    flag: "🇦🇬",
    code: "AG",
    dial_code: "+1268",
  },
  {
    name: "Argentina",
    flag: "🇦🇷",
    code: "AR",
    dial_code: "+54",
  },
  {
    name: "Armenia",
    flag: "🇦🇲",
    code: "AM",
    dial_code: "+374",
  },
  {
    name: "Aruba",
    flag: "🇦🇼",
    code: "AW",
    dial_code: "+297",
  },
  {
    name: "Australia",
    flag: "🇦🇺",
    code: "AU",
    dial_code: "+61",
  },
  {
    name: "Austria",
    flag: "🇦🇹",
    code: "AT",
    dial_code: "+43",
  },
  {
    name: "Azerbaijan",
    flag: "🇦🇿",
    code: "AZ",
    dial_code: "+994",
  },
  {
    name: "Bahamas",
    flag: "🇧🇸",
    code: "BS",
    dial_code: "+1242",
  },
  {
    name: "Bahrain",
    flag: "🇧🇭",
    code: "BH",
    dial_code: "+973",
  },
  {
    name: "Bangladesh",
    flag: "🇧🇩",
    code: "BD",
    dial_code: "+880",
  },
  {
    name: "Barbados",
    flag: "🇧🇧",
    code: "BB",
    dial_code: "+1246",
  },
  {
    name: "Belarus",
    flag: "🇧🇾",
    code: "BY",
    dial_code: "+375",
  },
  {
    name: "Belgium",
    flag: "🇧🇪",
    code: "BE",
    dial_code: "+32",
  },
  {
    name: "Belize",
    flag: "🇧🇿",
    code: "BZ",
    dial_code: "+501",
  },
  {
    name: "Benin",
    flag: "🇧🇯",
    code: "BJ",
    dial_code: "+229",
  },
  {
    name: "Bermuda",
    flag: "🇧🇲",
    code: "BM",
    dial_code: "+1441",
  },
  {
    name: "Bhutan",
    flag: "🇧🇹",
    code: "BT",
    dial_code: "+975",
  },
  {
    name: "Bolivia, Plurinational State of bolivia",
    flag: "🇧🇴",
    code: "BO",
    dial_code: "+591",
  },
  {
    name: "Bosnia and Herzegovina",
    flag: "🇧🇦",
    code: "BA",
    dial_code: "+387",
  },
  {
    name: "Botswana",
    flag: "🇧🇼",
    code: "BW",
    dial_code: "+267",
  },
  {
    name: "Bouvet Island",
    flag: "🇧🇻",
    code: "BV",
    dial_code: "+47",
  },
  {
    name: "Brazil",
    flag: "🇧🇷",
    code: "BR",
    dial_code: "+55",
  },
  {
    name: "British Indian Ocean Territory",
    flag: "🇮🇴",
    code: "IO",
    dial_code: "+246",
  },
  {
    name: "Brunei Darussalam",
    flag: "🇧🇳",
    code: "BN",
    dial_code: "+673",
  },
  {
    name: "Bulgaria",
    flag: "🇧🇬",
    code: "BG",
    dial_code: "+359",
  },
  {
    name: "Burkina Faso",
    flag: "🇧🇫",
    code: "BF",
    dial_code: "+226",
  },
  {
    name: "Burundi",
    flag: "🇧🇮",
    code: "BI",
    dial_code: "+257",
  },
  {
    name: "Cambodia",
    flag: "🇰🇭",
    code: "KH",
    dial_code: "+855",
  },
  {
    name: "Cameroon",
    flag: "🇨🇲",
    code: "CM",
    dial_code: "+237",
  },
  {
    name: "Canada",
    flag: "🇨🇦",
    code: "CA",
    dial_code: "+1",
  },
  {
    name: "Cape Verde",
    flag: "🇨🇻",
    code: "CV",
    dial_code: "+238",
  },
  {
    name: "Cayman Islands",
    flag: "🇰🇾",
    code: "KY",
    dial_code: "+345",
  },
  {
    name: "Central African Republic",
    flag: "🇨🇫",
    code: "CF",
    dial_code: "+236",
  },
  {
    name: "Chad",
    flag: "🇹🇩",
    code: "TD",
    dial_code: "+235",
  },
  {
    name: "Chile",
    flag: "🇨🇱",
    code: "CL",
    dial_code: "+56",
  },
  {
    name: "China",
    flag: "🇨🇳",
    code: "CN",
    dial_code: "+86",
  },
  {
    name: "Christmas Island",
    flag: "🇨🇽",
    code: "CX",
    dial_code: "+61",
  },
  {
    name: "Cocos (Keeling) Islands",
    flag: "🇨🇨",
    code: "CC",
    dial_code: "+61",
  },
  {
    name: "Colombia",
    flag: "🇨🇴",
    code: "CO",
    dial_code: "+57",
  },
  {
    name: "Comoros",
    flag: "🇰🇲",
    code: "KM",
    dial_code: "+269",
  },
  {
    name: "Congo",
    flag: "🇨🇬",
    code: "CG",
    dial_code: "+242",
  },
  {
    name: "Congo, The Democratic Republic of the Congo",
    flag: "🇨🇩",
    code: "CD",
    dial_code: "+243",
  },
  {
    name: "Cook Islands",
    flag: "🇨🇰",
    code: "CK",
    dial_code: "+682",
  },
  {
    name: "Costa Rica",
    flag: "🇨🇷",
    code: "CR",
    dial_code: "+506",
  },
  {
    name: "Cote d'Ivoire",
    flag: "🇨🇮",
    code: "CI",
    dial_code: "+225",
  },
  {
    name: "Croatia",
    flag: "🇭🇷",
    code: "HR",
    dial_code: "+385",
  },
  {
    name: "Cuba",
    flag: "🇨🇺",
    code: "CU",
    dial_code: "+53",
  },
  {
    name: "Cyprus",
    flag: "🇨🇾",
    code: "CY",
    dial_code: "+357",
  },
  {
    name: "Czech Republic",
    flag: "🇨🇿",
    code: "CZ",
    dial_code: "+420",
  },
  {
    name: "Denmark",
    flag: "🇩🇰",
    code: "DK",
    dial_code: "+45",
  },
  {
    name: "Djibouti",
    flag: "🇩🇯",
    code: "DJ",
    dial_code: "+253",
  },
  {
    name: "Dominica",
    flag: "🇩🇲",
    code: "DM",
    dial_code: "+1767",
  },
  {
    name: "Dominican Republic",
    flag: "🇩🇴",
    code: "DO",
    dial_code: "+1849",
  },
  {
    name: "Ecuador",
    flag: "🇪🇨",
    code: "EC",
    dial_code: "+593",
  },
  {
    name: "Egypt",
    flag: "🇪🇬",
    code: "EG",
    dial_code: "+20",
  },
  {
    name: "El Salvador",
    flag: "🇸🇻",
    code: "SV",
    dial_code: "+503",
  },
  {
    name: "Equatorial Guinea",
    flag: "🇬🇶",
    code: "GQ",
    dial_code: "+240",
  },
  {
    name: "Eritrea",
    flag: "🇪🇷",
    code: "ER",
    dial_code: "+291",
  },
  {
    name: "Estonia",
    flag: "🇪🇪",
    code: "EE",
    dial_code: "+372",
  },
  {
    name: "Ethiopia",
    flag: "🇪🇹",
    code: "ET",
    dial_code: "+251",
  },
  {
    name: "Falkland Islands (Malvinas)",
    flag: "🇫🇰",
    code: "FK",
    dial_code: "+500",
  },
  {
    name: "Faroe Islands",
    flag: "🇫🇴",
    code: "FO",
    dial_code: "+298",
  },
  {
    name: "Fiji",
    flag: "🇫🇯",
    code: "FJ",
    dial_code: "+679",
  },
  {
    name: "Finland",
    flag: "🇫🇮",
    code: "FI",
    dial_code: "+358",
  },
  {
    name: "France",
    flag: "🇫🇷",
    code: "FR",
    dial_code: "+33",
  },
  {
    name: "French Guiana",
    flag: "🇬🇫",
    code: "GF",
    dial_code: "+594",
  },
  {
    name: "French Polynesia",
    flag: "🇵🇫",
    code: "PF",
    dial_code: "+689",
  },
  {
    name: "French Southern Territories",
    flag: "🇹🇫",
    code: "TF",
    dial_code: "+262",
  },
  {
    name: "Gabon",
    flag: "🇬🇦",
    code: "GA",
    dial_code: "+241",
  },
  {
    name: "Gambia",
    flag: "🇬🇲",
    code: "GM",
    dial_code: "+220",
  },
  {
    name: "Georgia",
    flag: "🇬🇪",
    code: "GE",
    dial_code: "+995",
  },
  {
    name: "Germany",
    flag: "🇩🇪",
    code: "DE",
    dial_code: "+49",
  },
  {
    name: "Ghana",
    flag: "🇬🇭",
    code: "GH",
    dial_code: "+233",
  },
  {
    name: "Gibraltar",
    flag: "🇬🇮",
    code: "GI",
    dial_code: "+350",
  },
  {
    name: "Greece",
    flag: "🇬🇷",
    code: "GR",
    dial_code: "+30",
  },
  {
    name: "Greenland",
    flag: "🇬🇱",
    code: "GL",
    dial_code: "+299",
  },
  {
    name: "Grenada",
    flag: "🇬🇩",
    code: "GD",
    dial_code: "+1473",
  },
  {
    name: "Guadeloupe",
    flag: "🇬🇵",
    code: "GP",
    dial_code: "+590",
  },
  {
    name: "Guam",
    flag: "🇬🇺",
    code: "GU",
    dial_code: "+1671",
  },
  {
    name: "Guatemala",
    flag: "🇬🇹",
    code: "GT",
    dial_code: "+502",
  },
  {
    name: "Guernsey",
    flag: "🇬🇬",
    code: "GG",
    dial_code: "+44",
  },
  {
    name: "Guinea",
    flag: "🇬🇳",
    code: "GN",
    dial_code: "+224",
  },
  {
    name: "Guinea-Bissau",
    flag: "🇬🇼",
    code: "GW",
    dial_code: "+245",
  },
  {
    name: "Guyana",
    flag: "🇬🇾",
    code: "GY",
    dial_code: "+592",
  },
  {
    name: "Haiti",
    flag: "🇭🇹",
    code: "HT",
    dial_code: "+509",
  },
  {
    name: "Heard Island and Mcdonald Islands",
    flag: "🇭🇲",
    code: "HM",
    dial_code: "+672",
  },
  {
    name: "Holy See (Vatican City State)",
    flag: "🇻🇦",
    code: "VA",
    dial_code: "+379",
  },
  {
    name: "Honduras",
    flag: "🇭🇳",
    code: "HN",
    dial_code: "+504",
  },
  {
    name: "Hong Kong",
    flag: "🇭🇰",
    code: "HK",
    dial_code: "+852",
  },
  {
    name: "Hungary",
    flag: "🇭🇺",
    code: "HU",
    dial_code: "+36",
  },
  {
    name: "Iceland",
    flag: "🇮🇸",
    code: "IS",
    dial_code: "+354",
  },
  {
    name: "India",
    flag: "🇮🇳",
    code: "IN",
    dial_code: "+91",
  },
  {
    name: "Indonesia",
    flag: "🇮🇩",
    code: "ID",
    dial_code: "+62",
  },
  {
    name: "Iran, Islamic Republic of Persian Gulf",
    flag: "🇮🇷",
    code: "IR",
    dial_code: "+98",
  },
  {
    name: "Iraq",
    flag: "🇮🇶",
    code: "IQ",
    dial_code: "+964",
  },
  {
    name: "Ireland",
    flag: "🇮🇪",
    code: "IE",
    dial_code: "+353",
  },
  {
    name: "Isle of Man",
    flag: "🇮🇲",
    code: "IM",
    dial_code: "+44",
  },
  {
    name: "Israel",
    flag: "🇮🇱",
    code: "IL",
    dial_code: "+972",
  },
  {
    name: "Italy",
    flag: "🇮🇹",
    code: "IT",
    dial_code: "+39",
  },
  {
    name: "Jamaica",
    flag: "🇯🇲",
    code: "JM",
    dial_code: "+1876",
  },
  {
    name: "Japan",
    flag: "🇯🇵",
    code: "JP",
    dial_code: "+81",
  },
  {
    name: "Jersey",
    flag: "🇯🇪",
    code: "JE",
    dial_code: "+44",
  },
  {
    name: "Jordan",
    flag: "🇯🇴",
    code: "JO",
    dial_code: "+962",
  },
  {
    name: "Kazakhstan",
    flag: "🇰🇿",
    code: "KZ",
    dial_code: "+7",
  },
  {
    name: "Kenya",
    flag: "🇰🇪",
    code: "KE",
    dial_code: "+254",
  },
  {
    name: "Kiribati",
    flag: "🇰🇮",
    code: "KI",
    dial_code: "+686",
  },
  {
    name: "Korea, Democratic People's Republic of Korea",
    flag: "🇰🇵",
    code: "KP",
    dial_code: "+850",
  },
  {
    name: "Korea, Republic of South Korea",
    flag: "🇰🇷",
    code: "KR",
    dial_code: "+82",
  },
  {
    name: "Kosovo",
    flag: "🇽🇰",
    code: "XK",
    dial_code: "+383",
  },
  {
    name: "Kuwait",
    flag: "🇰🇼",
    code: "KW",
    dial_code: "+965",
  },
  {
    name: "Kyrgyzstan",
    flag: "🇰🇬",
    code: "KG",
    dial_code: "+996",
  },
  {
    name: "Laos",
    flag: "🇱🇦",
    code: "LA",
    dial_code: "+856",
  },
  {
    name: "Latvia",
    flag: "🇱🇻",
    code: "LV",
    dial_code: "+371",
  },
  {
    name: "Lebanon",
    flag: "🇱🇧",
    code: "LB",
    dial_code: "+961",
  },
  {
    name: "Lesotho",
    flag: "🇱🇸",
    code: "LS",
    dial_code: "+266",
  },
  {
    name: "Liberia",
    flag: "🇱🇷",
    code: "LR",
    dial_code: "+231",
  },
  {
    name: "Libyan Arab Jamahiriya",
    flag: "🇱🇾",
    code: "LY",
    dial_code: "+218",
  },
  {
    name: "Liechtenstein",
    flag: "🇱🇮",
    code: "LI",
    dial_code: "+423",
  },
  {
    name: "Lithuania",
    flag: "🇱🇹",
    code: "LT",
    dial_code: "+370",
  },
  {
    name: "Luxembourg",
    flag: "🇱🇺",
    code: "LU",
    dial_code: "+352",
  },
  {
    name: "Macao",
    flag: "🇲🇴",
    code: "MO",
    dial_code: "+853",
  },
  {
    name: "Macedonia",
    flag: "🇲🇰",
    code: "MK",
    dial_code: "+389",
  },
  {
    name: "Madagascar",
    flag: "🇲🇬",
    code: "MG",
    dial_code: "+261",
  },
  {
    name: "Malawi",
    flag: "🇲🇼",
    code: "MW",
    dial_code: "+265",
  },
  {
    name: "Malaysia",
    flag: "🇲🇾",
    code: "MY",
    dial_code: "+60",
  },
  {
    name: "Maldives",
    flag: "🇲🇻",
    code: "MV",
    dial_code: "+960",
  },
  {
    name: "Mali",
    flag: "🇲🇱",
    code: "ML",
    dial_code: "+223",
  },
  {
    name: "Malta",
    flag: "🇲🇹",
    code: "MT",
    dial_code: "+356",
  },
  {
    name: "Marshall Islands",
    flag: "🇲🇭",
    code: "MH",
    dial_code: "+692",
  },
  {
    name: "Martinique",
    flag: "🇲🇶",
    code: "MQ",
    dial_code: "+596",
  },
  {
    name: "Mauritania",
    flag: "🇲🇷",
    code: "MR",
    dial_code: "+222",
  },
  {
    name: "Mauritius",
    flag: "🇲🇺",
    code: "MU",
    dial_code: "+230",
  },
  {
    name: "Mayotte",
    flag: "🇾🇹",
    code: "YT",
    dial_code: "+262",
  },
  {
    name: "Mexico",
    flag: "🇲🇽",
    code: "MX",
    dial_code: "+52",
  },
  {
    name: "Micronesia, Federated States of Micronesia",
    flag: "🇫🇲",
    code: "FM",
    dial_code: "+691",
  },
  {
    name: "Moldova",
    flag: "🇲🇩",
    code: "MD",
    dial_code: "+373",
  },
  {
    name: "Monaco",
    flag: "🇲🇨",
    code: "MC",
    dial_code: "+377",
  },
  {
    name: "Mongolia",
    flag: "🇲🇳",
    code: "MN",
    dial_code: "+976",
  },
  {
    name: "Montenegro",
    flag: "🇲🇪",
    code: "ME",
    dial_code: "+382",
  },
  {
    name: "Montserrat",
    flag: "🇲🇸",
    code: "MS",
    dial_code: "+1664",
  },
  {
    name: "Morocco",
    flag: "🇲🇦",
    code: "MA",
    dial_code: "+212",
  },
  {
    name: "Mozambique",
    flag: "🇲🇿",
    code: "MZ",
    dial_code: "+258",
  },
  {
    name: "Myanmar",
    flag: "🇲🇲",
    code: "MM",
    dial_code: "+95",
  },
  {
    name: "Namibia",
    flag: "🇳🇦",
    code: "NA",
    dial_code: "+264",
  },
  {
    name: "Nauru",
    flag: "🇳🇷",
    code: "NR",
    dial_code: "+674",
  },
  {
    name: "Nepal",
    flag: "🇳🇵",
    code: "NP",
    dial_code: "+977",
  },
  {
    name: "Netherlands",
    flag: "🇳🇱",
    code: "NL",
    dial_code: "+31",
  },
  {
    name: "Netherlands Antilles",
    flag: "",
    code: "AN",
    dial_code: "+599",
  },
  {
    name: "New Caledonia",
    flag: "🇳🇨",
    code: "NC",
    dial_code: "+687",
  },
  {
    name: "New Zealand",
    flag: "🇳🇿",
    code: "NZ",
    dial_code: "+64",
  },
  {
    name: "Nicaragua",
    flag: "🇳🇮",
    code: "NI",
    dial_code: "+505",
  },
  {
    name: "Niger",
    flag: "🇳🇪",
    code: "NE",
    dial_code: "+227",
  },
  {
    name: "Nigeria",
    flag: "🇳🇬",
    code: "NG",
    dial_code: "+234",
  },
  {
    name: "Niue",
    flag: "🇳🇺",
    code: "NU",
    dial_code: "+683",
  },
  {
    name: "Norfolk Island",
    flag: "🇳🇫",
    code: "NF",
    dial_code: "+672",
  },
  {
    name: "Northern Mariana Islands",
    flag: "🇲🇵",
    code: "MP",
    dial_code: "+1670",
  },
  {
    name: "Norway",
    flag: "🇳🇴",
    code: "NO",
    dial_code: "+47",
  },
  {
    name: "Oman",
    flag: "🇴🇲",
    code: "OM",
    dial_code: "+968",
  },
  {
    name: "Pakistan",
    flag: "🇵🇰",
    code: "PK",
    dial_code: "+92",
  },
  {
    name: "Palau",
    flag: "🇵🇼",
    code: "PW",
    dial_code: "+680",
  },
  {
    name: "Palestinian Territory, Occupied",
    flag: "🇵🇸",
    code: "PS",
    dial_code: "+970",
  },
  {
    name: "Panama",
    flag: "🇵🇦",
    code: "PA",
    dial_code: "+507",
  },
  {
    name: "Papua New Guinea",
    flag: "🇵🇬",
    code: "PG",
    dial_code: "+675",
  },
  {
    name: "Paraguay",
    flag: "🇵🇾",
    code: "PY",
    dial_code: "+595",
  },
  {
    name: "Peru",
    flag: "🇵🇪",
    code: "PE",
    dial_code: "+51",
  },
  {
    name: "Philippines",
    flag: "🇵🇭",
    code: "PH",
    dial_code: "+63",
  },
  {
    name: "Pitcairn",
    flag: "🇵🇳",
    code: "PN",
    dial_code: "+64",
  },
  {
    name: "Poland",
    flag: "🇵🇱",
    code: "PL",
    dial_code: "+48",
  },
  {
    name: "Portugal",
    flag: "🇵🇹",
    code: "PT",
    dial_code: "+351",
  },
  {
    name: "Puerto Rico",
    flag: "🇵🇷",
    code: "PR",
    dial_code: "+1939",
  },
  {
    name: "Qatar",
    flag: "🇶🇦",
    code: "QA",
    dial_code: "+974",
  },
  {
    name: "Romania",
    flag: "🇷🇴",
    code: "RO",
    dial_code: "+40",
  },
  {
    name: "Russia",
    flag: "🇷🇺",
    code: "RU",
    dial_code: "+7",
  },
  {
    name: "Rwanda",
    flag: "🇷🇼",
    code: "RW",
    dial_code: "+250",
  },
  {
    name: "Reunion",
    flag: "🇷🇪",
    code: "RE",
    dial_code: "+262",
  },
  {
    name: "Saint Barthelemy",
    flag: "🇧🇱",
    code: "BL",
    dial_code: "+590",
  },
  {
    name: "Saint Helena, Ascension and Tristan Da Cunha",
    flag: "🇸🇭",
    code: "SH",
    dial_code: "+290",
  },
  {
    name: "Saint Kitts and Nevis",
    flag: "🇰🇳",
    code: "KN",
    dial_code: "+1869",
  },
  {
    name: "Saint Lucia",
    flag: "🇱🇨",
    code: "LC",
    dial_code: "+1758",
  },
  {
    name: "Saint Martin",
    flag: "🇲🇫",
    code: "MF",
    dial_code: "+590",
  },
  {
    name: "Saint Pierre and Miquelon",
    flag: "🇵🇲",
    code: "PM",
    dial_code: "+508",
  },
  {
    name: "Saint Vincent and the Grenadines",
    flag: "🇻🇨",
    code: "VC",
    dial_code: "+1784",
  },
  {
    name: "Samoa",
    flag: "🇼🇸",
    code: "WS",
    dial_code: "+685",
  },
  {
    name: "San Marino",
    flag: "🇸🇲",
    code: "SM",
    dial_code: "+378",
  },
  {
    name: "Sao Tome and Principe",
    flag: "🇸🇹",
    code: "ST",
    dial_code: "+239",
  },
  {
    name: "Saudi Arabia",
    flag: "🇸🇦",
    code: "SA",
    dial_code: "+966",
  },
  {
    name: "Senegal",
    flag: "🇸🇳",
    code: "SN",
    dial_code: "+221",
  },
  {
    name: "Serbia",
    flag: "🇷🇸",
    code: "RS",
    dial_code: "+381",
  },
  {
    name: "Seychelles",
    flag: "🇸🇨",
    code: "SC",
    dial_code: "+248",
  },
  {
    name: "Sierra Leone",
    flag: "🇸🇱",
    code: "SL",
    dial_code: "+232",
  },
  {
    name: "Singapore",
    flag: "🇸🇬",
    code: "SG",
    dial_code: "+65",
  },
  {
    name: "Slovakia",
    flag: "🇸🇰",
    code: "SK",
    dial_code: "+421",
  },
  {
    name: "Slovenia",
    flag: "🇸🇮",
    code: "SI",
    dial_code: "+386",
  },
  {
    name: "Solomon Islands",
    flag: "🇸🇧",
    code: "SB",
    dial_code: "+677",
  },
  {
    name: "Somalia",
    flag: "🇸🇴",
    code: "SO",
    dial_code: "+252",
  },
  {
    name: "South Africa",
    flag: "🇿🇦",
    code: "ZA",
    dial_code: "+27",
  },
  {
    name: "South Sudan",
    flag: "🇸🇸",
    code: "SS",
    dial_code: "+211",
  },
  {
    name: "South Georgia and the South Sandwich Islands",
    flag: "🇬🇸",
    code: "GS",
    dial_code: "+500",
  },
  {
    name: "Spain",
    flag: "🇪🇸",
    code: "ES",
    dial_code: "+34",
  },
  {
    name: "Sri Lanka",
    flag: "🇱🇰",
    code: "LK",
    dial_code: "+94",
  },
  {
    name: "Sudan",
    flag: "🇸🇩",
    code: "SD",
    dial_code: "+249",
  },
  {
    name: "Suriname",
    flag: "🇸🇷",
    code: "SR",
    dial_code: "+597",
  },
  {
    name: "Svalbard and Jan Mayen",
    flag: "🇸🇯",
    code: "SJ",
    dial_code: "+47",
  },
  {
    name: "Eswatini",
    flag: "🇸🇿",
    code: "SZ",
    dial_code: "+268",
  },
  {
    name: "Sweden",
    flag: "🇸🇪",
    code: "SE",
    dial_code: "+46",
  },
  {
    name: "Switzerland",
    flag: "🇨🇭",
    code: "CH",
    dial_code: "+41",
  },
  {
    name: "Syrian Arab Republic",
    flag: "🇸🇾",
    code: "SY",
    dial_code: "+963",
  },
  {
    name: "Taiwan",
    flag: "🇹🇼",
    code: "TW",
    dial_code: "+886",
  },
  {
    name: "Tajikistan",
    flag: "🇹🇯",
    code: "TJ",
    dial_code: "+992",
  },
  {
    name: "Tanzania, United Republic of Tanzania",
    flag: "🇹🇿",
    code: "TZ",
    dial_code: "+255",
  },
  {
    name: "Thailand",
    flag: "🇹🇭",
    code: "TH",
    dial_code: "+66",
  },
  {
    name: "Timor-Leste",
    flag: "🇹🇱",
    code: "TL",
    dial_code: "+670",
  },
  {
    name: "Togo",
    flag: "🇹🇬",
    code: "TG",
    dial_code: "+228",
  },
  {
    name: "Tokelau",
    flag: "🇹🇰",
    code: "TK",
    dial_code: "+690",
  },
  {
    name: "Tonga",
    flag: "🇹🇴",
    code: "TO",
    dial_code: "+676",
  },
  {
    name: "Trinidad and Tobago",
    flag: "🇹🇹",
    code: "TT",
    dial_code: "+1868",
  },
  {
    name: "Tunisia",
    flag: "🇹🇳",
    code: "TN",
    dial_code: "+216",
  },
  {
    name: "Turkey",
    flag: "🇹🇷",
    code: "TR",
    dial_code: "+90",
  },
  {
    name: "Turkmenistan",
    flag: "🇹🇲",
    code: "TM",
    dial_code: "+993",
  },
  {
    name: "Turks and Caicos Islands",
    flag: "🇹🇨",
    code: "TC",
    dial_code: "+1649",
  },
  {
    name: "Tuvalu",
    flag: "🇹🇻",
    code: "TV",
    dial_code: "+688",
  },
  {
    name: "Uganda",
    flag: "🇺🇬",
    code: "UG",
    dial_code: "+256",
  },
  {
    name: "Ukraine",
    flag: "🇺🇦",
    code: "UA",
    dial_code: "+380",
  },
  {
    name: "United Arab Emirates",
    flag: "🇦🇪",
    code: "AE",
    dial_code: "+971",
  },
  {
    name: "United Kingdom",
    flag: "🇬🇧",
    code: "GB",
    dial_code: "+44",
  },
  {
    name: "United States",
    flag: "🇺🇸",
    code: "US",
    dial_code: "+1",
  },
  {
    name: "Uruguay",
    flag: "🇺🇾",
    code: "UY",
    dial_code: "+598",
  },
  {
    name: "Uzbekistan",
    flag: "🇺🇿",
    code: "UZ",
    dial_code: "+998",
  },
  {
    name: "Vanuatu",
    flag: "🇻🇺",
    code: "VU",
    dial_code: "+678",
  },
  {
    name: "Venezuela, Bolivarian Republic of Venezuela",
    flag: "🇻🇪",
    code: "VE",
    dial_code: "+58",
  },
  {
    name: "Vietnam",
    flag: "🇻🇳",
    code: "VN",
    dial_code: "+84",
  },
  {
    name: "Virgin Islands, British",
    flag: "🇻🇬",
    code: "VG",
    dial_code: "+1284",
  },
  {
    name: "Virgin Islands, U.S.",
    flag: "🇻🇮",
    code: "VI",
    dial_code: "+1340",
  },
  {
    name: "Wallis and Futuna",
    flag: "🇼🇫",
    code: "WF",
    dial_code: "+681",
  },
  {
    name: "Yemen",
    flag: "🇾🇪",
    code: "YE",
    dial_code: "+967",
  },
  {
    name: "Zambia",
    flag: "🇿🇲",
    code: "ZM",
    dial_code: "+260",
  },
  {
    name: "Zimbabwe",
    flag: "🇿🇼",
    code: "ZW",
    dial_code: "+263",
  },
];

export const noticePeriods = [
  { title: "15 Days or less", value: "15 days or less" },
  { title: "1 Month", value: "1 month" },
  { title: "2 Months", value: "2 months" },
  { title: "3 Months", value: "3 months" },
  { title: "More Than 3 Months", value: "more than 3 months" },
];

export const inputData = [
  {
    title: "Sort by",
    img: "/images/jobs/arw.png",
    child: ["Recommended", "Relevant", "Recently Posted"],
  },
  {
    title: "Job type",
    img: "/images/jobs/arw.png",

    child: ["pune", "mumbai", "chennai"],
  },
  {
    title: "Date posted",
    img: "/images/jobs/arw.png",
    child: ["Anytime", "Past Month", "Past Week"],
  },
  {
    title: "Industry",
    img: "/images/jobs/arw.png",
    child: [
      "Other",
      "IT/ Computers - Software",
      "Banking/ Accounting/Financial Services",
      "Internet/ E-commerce",
      "Education/ Training",
      "Entertainment/ Media/ Publishing",
      "IT/Computers - Hardware & Networking",
      "Engineering & Design",
      "FMCG",
      "Automotive/Automobile/Ancillaries",
    ],
  },
  {
    title: "Salary",
    img: "/images/jobs/arw.png",
    child: [
      "$ 0-1 Lakhs",
      "$ 0-1 Lakhs",
      "$ 0-1 Lakhs",
      "$ 0-1 Lakhs",
      "$ 0-1 Lakhs",
      "$ 0-1 Lakhs",
      "Not Specified",
    ],
  },
  {
    title: "Experience",
    img: "/images/jobs/arw.png",
    child: [
      "0-1 Years",
      "0-1 Years",
      "0-1 Years",
      "0-1 Years",
      "0-1 Years",
      "0-1 Years",
      "0-1 Years",
    ],
  },
  {
    title: "Education",
    img: "/images/jobs/arw.png",
    child: [
      "Bachelor Of Technology (B.Tech/B.E)",
      "Bachelor Of Computer Application (B.C.A)",
      "Bachelor of Design (B.Des.)",
      "Master of Science (MS/M.Sc)",
      "Masters in Technology (M.Tech/M.E)",
      "Bachelor Of Technology (B.Tech/B.E)",
      "Bachelor Of Technology (B.Tech/B.E)",
      "Bachelor Of Technology (B.Tech/B.E)",
      "Bachelor Of Technology (B.Tech/B.E)",
      "Bachelor Of Technology (B.Tech/B.E)",
    ],
  },

  {
    title: "Job mode",
    img: "/images/jobs/arw.png",
    child: [
      "On-site",
      "On-site",
      "On-site",
      "On-site",
      "On-site",
      "On-site",
      "On-site",
    ],
  },
];

export const City = [
  "Mumbai",
  "Delhi",
  "Bangalore",
  "Hyderabad",
  "Chennai",
  "Kolkata",
  "Ahmedabad",
  "Pune",
  "Surat",
  "Jaipur",
  "Lucknow",
  "Kanpur",
  "Nagpur",
  "Indore",
  "Thane",
  "Bhopal",
  "Visakhapatnam",
  "Pimpri-Chinchwad",
  "Patna",
  "Vadodara",
  "Ghaziabad",
  "Ludhiana",
  "Agra",
  "Nashik",
  "Faridabad",
  "Meerut",
  "Rajkot",
  "Kalyan-Dombivali",
  "Vasai-Virar",
  "Varanasi",
  "Srinagar",
  "Aurangabad",
  "Dhanbad",
  "Amritsar",
  "Navi Mumbai",
  "Allahabad",
  "Ranchi",
  "Howrah",
  "Jabalpur",
  "Gwalior",
  "Vijayawada",
  "Jodhpur",
  "Madurai",
  "Raipur",
  "Kota",
  "Guwahati",
  "Chandigarh",
  "Solapur",
  "Hubballi-Dharwad",
  "Bareilly",
  "Moradabad",
  "Mysuru",
  "Gurgaon",
  "Aligarh",
  "Jalandhar",
  "Tiruchirappalli",
  "Bhubaneswar",
  "Salem",
  "Mira-Bhayandar",
  "Warangal",
  "Thiruvananthapuram",
  "Bhiwandi",
  "Saharanpur",
  "Guntur",
  "Amravati",
  "Bikaner",
  "Noida",
  "Jamshedpur",
  "Bhilai",
  "Cuttack",
  "Kochi",
  "Udaipur",
  "Bhavnagar",
  "Dehradun",
  "Asansol",
  "Nanded",
  "Ajmer",
  "Jamnagar",
  "Ujjain",
  "Sangli",
  "Loni",
  "Jhansi",
  "Pondicherry",
  "Nellore",
  "Jammu",
  "Belagavi",
  "Raurkela",
  "Mangaluru",
  "Tirunelveli",
  "Malegaon",
  "Gaya",
  "Tiruppur",
  "Davanagere",
  "Kozhikode",
  "Akola",
  "Kurnool",
  "Bokaro",
  "Rajahmundry",
  "Ballari",
  "Agartala",
  "Bhagalpur",
  "Latur",
  "Dhule",
  "Korba",
  "Bhilwara",
  "Brahmapur",
  "Mysuru",
  "Muzaffarpur",
  "Ahmednagar",
  "Kollam",
  "Raghunathganj",
  "Bilaspur",
  "Shahjahanpur",
  "Thrissur",
  "Alwar",
  "Kakinada",
  "Nizamabad",
  "Sagar",
  "Tumkur",
  "Hisar",
  "Rohtak",
  "Panipat",
  "Darbhanga",
  "Kharagpur",
  "Aizawl",
  "Ichalkaranji",
  "Tirupati",
  "Karnal",
  "Bathinda",
  "Rampur",
  "Shivamogga",
  "Ratlam",
  "Modinagar",
  "Durg",
  "Shillong",
  "Imphal",
  "Hapur",
  "Ranipet",
  "Anantapur",
  "Arrah",
  "Karimnagar",
  "Parbhani",
  "Etawah",
  "Bharatpur",
  "Begusarai",
  "New Delhi",
  "Chhapra",
  "Kadapa",
  "Ramagundam",
  "Pali",
  "Satna",
  "Vizianagaram",
  "Katihar",
  "Hardwar",
  "Sonipat",
  "Nagercoil",
  "Thanjavur",
  "Murwara",
  "Naihati",
  "Sambhal",
  "Nadiad",
  "Yamunanagar",
  "English Bazar",
  "Eluru",
  "Munger",
  "Panchkula",
  "Raayachuru",
  "Panvel",
  "Deoghar",
  "Ongole",
  "Nandyal",
  "Morena",
  "Bhiwani",
  "Porbandar",
  "Palakkad",
  "Anand",
  "Purnia",
  "Baharampur",
  "Barmer",
  "Morvi",
  "Orai",
  "Bahraich",
  "Sikar",
  "Vellore",
  "Alappuzha",
  "Shahjanpur",
  "Karnal",
  "Hosur",
  "Adityapur",
  "Ambernath",
  "Bhusawal",
  "Barasat",
  "Khammam",
  "Azhikode",
  "Bharatpur",
  "Kharagpur",
  "Beed",
  "Bettiah",
  "Madhyamgram",
  "Mango",
  "Kanchipuram",
  "Nehru Nagar",
  "Bhilai",
  "Deoria",
  "Bidar",
  "Tiruchengode",
  "Gangawati",
  "Suratgarh",
  "Haldia",
  "Hoskote",
  "Dibrugarh",
  "Arambagh",
  "Kalpetta",
  "Karimganj",
  "Malappuram",
  "Palwal",
  "Sangrur",
  "Unnao",
  "Palanpur",
  "Baranagar",
  "Gudivada",
  "Akot",
  "Vatakara",
  "Tenali",
  "Sirsilla",
  "Pusad",
  "Motihari",
  "Pudukkottai",
  "Guntakal",
  "Dharmavaram",
  "Jorhat",
  "Batala",
  "Jhunjhunu",
  "Chittoor",
  "Palitana",
  "Ranaghat",
  "Sambalpur",
];

export const templates = [
  {
    title: "Template1",
    imgUrl: "/images/templates/template1.png",
    index: 1,
    fontFamily: "Lato",
    themeColor: "#414042",
    formFields: ["hobbies"],
  },
  {
    title: "Template2",
    imgUrl: "/images/templates/template2.png",
    index: 2,
    fontFamily: "Barlow",
    themeColor: "#F7902B",
    formFields: ["languages"],
  },
  {
    title: "Template3",
    imgUrl: "/images/templates/template3.png",
    index: 3,
    fontFamily: "Inter",
    themeColor: "#414042",
    formFields: ["language", "hobbies"],
  },
  {
    title: "Template4",
    imgUrl: "/images/templates/template4.png",
    index: 4,
    fontFamily: "Montserrat",
    themeColor: "#00AEEF",
    formFields: ["language", "hobbies"],
  },
  {
    title: "Template5",
    imgUrl: "/images/templates/template5.png",
    index: 5,
    fontFamily: "Kanit",
    themeColor: "#316059",
    formFields: ["language"],
  },
  {
    title: "Template6",
    imgUrl: "/images/templates/template6.png",
    index: 6,
    fontFamily: "Lato",
    themeColor: "#FFC20E",
    formFields: ["language", "hobbies"],
  },
  {
    title: "Template7",
    imgUrl: "/images/templates/template7.png",
    index: 7,
    fontFamily: "Montserrat",
    themeColor: "#0077F9",
    formFields: ["course", "hobbies", "language"],
  },
  {
    title: "Template8",
    imgUrl: "/images/templates/template8.png",
    index: 8,
    fontFamily: "Montserrat",
    themeColor: "#646464",
  },
  {
    title: "Template9",
    imgUrl: "/images/templates/template9.png",
    index: 9,
    fontFamily: "Montserrat",
    themeColor: "#FFD740",
  },
  {
    title: "Template10",
    imgUrl: "/images/templates/template10.png",
    index: 10,
    fontFamily: "Inter",
    themeColor: "#F2BE5C",
    formFields: ["course", "language", "tools"],
  },
  {
    title: "Template11",
    imgUrl: "/images/templates/template11.png",
    index: 11,
    fontFamily: "Montserrat",
    themeColor: "#E6E7E8",
    formFields: ["course", "hobbies"],
  },
  {
    title: "Template12",
    imgUrl: "/images/templates/template12.png",
    index: 12,
    fontFamily: "Lato",
    themeColor: "#0C2438",
    formFields: ["language", "hobbies"],
  },
  {
    title: "Template13",
    imgUrl: "/images/templates/template13.png",
    index: 13,
    fontFamily: "Poppins",
    themeColor: "#0E6CC2",
    formFields: ["language", "hobbies"],
  },
  {
    title: "Template14",
    imgUrl: "/images/templates/template14.png",
    index: 14,
    fontFamily: "Inter",
    themeColor: "#242424",
    formFields: ["language", "hobbies", "course"],
  },
  {
    title: "Template15",
    imgUrl: "/images/templates/template15.png",
    index: 15,
    fontFamily: "Inter",
    themeColor: "#716D6D",
    formFields: ["hobbies", "course"],
  },
  {
    title: "Template16",
    imgUrl: "/images/templates/template53.png",
    index: 16,
    fontFamily: "Inter",
    themeColor: "#545554",
    formFields: ["language"],
  },
  {
    title: "Template17",
    imgUrl: "/images/templates/template17.png",
    index: 17,
    fontFamily: "Montserrat",
    themeColor: "#D1D2D3",
    formFields: ["language", "hobbies", "course"],
  },
  {
    title: "Template18",
    imgUrl: "/images/templates/template18.png",
    index: 18,
    fontFamily: "Montserrat",
    themeColor: "#F1F1F1",
    formFields: ["language"],
  },
  {
    title: "Template19",
    imgUrl: "/images/templates/template19.png",
    index: 19,
    fontFamily: "Inter",
    themeColor: "#000000",
    formFields: ["socialLinks", "hobbies"],
  },
  {
    title: "Template20",
    imgUrl: "/images/templates/template20.png",
    index: 20,
    fontFamily: "Montserrat",
    themeColor: "#303030",
    formFields: ["hobbies", "course", "language"],
  },
  {
    title: "Template21",
    imgUrl: "/images/templates/template21.png",
    index: 21,
    fontFamily: "Montserrat",
    themeColor: "#494949",
  },
  {
    title: "Template22",
    imgUrl: "/images/templates/template22.png",
    index: 22,
    fontFamily: "Inter",
    themeColor: "#000000",
  },
  {
    title: "Template23",
    imgUrl: "/images/templates/template23.png",
    index: 23,
    fontFamily: "Inter",
    themeColor: "#000000",
  },
  {
    title: "Template24",
    imgUrl: "/images/templates/template24.png",
    index: 24,
    fontFamily: "Poppins",
    themeColor: "#FBEDE4",
  },
  {
    title: "Template25",
    imgUrl: "/images/templates/template25.png",
    index: 25,
    fontFamily: "Montserrat",
    themeColor: "#414042",
  },
  {
    title: "Template26",
    imgUrl: "/images/templates/template26.png",
    index: 26,
    fontFamily: "Montserrat",
    themeColor: "#414042",
  },
  {
    title: "Template27",
    imgUrl: "/images/templates/template27.png",
    index: 27,
    fontFamily: "Inter",
    themeColor: "#CB3122",
  },
  {
    title: "Template28",
    imgUrl: "/images/templates/template28.png",
    index: 28,
    fontFamily: "Inter",
    themeColor: "#2AB6BB",
  },
  {
    title: "Template29",
    imgUrl: "/images/templates/template29.png",
    index: 29,
    fontFamily: "Montserrat",
    themeColor: "#324955",
  },
  {
    title: "Template30",
    imgUrl: "/images/templates/template30.png",
    index: 30,
    fontFamily: "Montserrat",
    themeColor: "#0054A6",
  },
  {
    title: "Template31",
    imgUrl: "/images/templates/template31.png",
    index: 31,
    fontFamily: "Poppins",
    themeColor: "#227CFF",
  },
  {
    title: "Template32",
    imgUrl: "/images/templates/template32.png",
    index: 32,
    fontFamily: "Lato",
    themeColor: "#0072BC",
  },
  {
    title: "Template33",
    imgUrl: "/images/templates/template33.png",
    index: 33,
    fontFamily: "Kanit",
    themeColor: "#414042",
  },
  {
    title: "Template34",
    imgUrl: "/images/templates/template34.png",
    index: 34,
    fontFamily: "Poppins",
    themeColor: "#6C83B7",
  },
  {
    title: "Template35",
    imgUrl: "/images/templates/template35.png",
    index: 35,
    fontFamily: "Lato",
    themeColor: "#B3977F",
  },
  {
    title: "Template36",
    imgUrl: "/images/templates/template36.png",
    index: 36,
    fontFamily: "Lato",
    themeColor: "#F15A29",
  },
  {
    title: "Template37",
    imgUrl: "/images/templates/template37.png",
    index: 37,
    fontFamily: "Inter",
    themeColor: "#3956A3",
  },
  {
    title: "Template38",
    imgUrl: "/images/templates/template38.png",
    index: 38,
    fontFamily: "Lato",
    themeColor: "#C49A6C",
  },
  {
    title: "Template39",
    imgUrl: "/images/templates/template39.png",
    index: 39,
    fontFamily: "Lato",
    themeColor: "#030203",
  },
  {
    title: "Template40",
    imgUrl: "/images/templates/template40.png",
    index: 40,
    fontFamily: "Lato",
    themeColor: "#47484C",
  },
  {
    title: "Template41",
    imgUrl: "/images/templates/template41.png",
    index: 41,
    fontFamily: "Inter",
    themeColor: "#EDEDEE",
  },
  {
    title: "Template42",
    imgUrl: "/images/templates/template42.png",
    index: 42,
    fontFamily: "Lato",
    themeColor: "#414042",
  },
  {
    title: "Template43",
    imgUrl: "/images/templates/template43.png",
    index: 43,
    fontFamily: "Montserrat",
    themeColor: "#F9D3D0",
  },
  {
    title: "Template44",
    imgUrl: "/images/templates/template44.png",
    index: 44,
    fontFamily: "Inter",
    themeColor: "#C7EAFB",
  },
  {
    title: "Template45",
    imgUrl: "/images/templates/template45.png",
    index: 45,
    fontFamily: "Lato",
    themeColor: "#9E071C",
  },
  {
    title: "Template46",
    imgUrl: "/images/templates/template46.png",
    index: 46,
    fontFamily: "Lato",
    themeColor: "#00AEEF",
  },
  {
    title: "Template47",
    imgUrl: "/images/templates/template47.png",
    index: 47,
    fontFamily: "Poppins",
    themeColor: "#27AAE1",
  },
  {
    title: "Template48",
    imgUrl: "/images/templates/template48.png",
    index: 48,
    fontFamily: "Poppins",
    themeColor: "#F7941D",
  },
  {
    title: "Template49",
    imgUrl: "/images/templates/template49.png",
    index: 49,
    fontFamily: "Poppins",
    themeColor: "#27AAE1",
  },
  {
    title: "Template50",
    imgUrl: "/images/templates/template50.png",
    index: 50,
    fontFamily: "Inter",
    themeColor: "#1C75BC",
  },
  {
    title: "Template51",
    imgUrl: "/images/templates/template51.png",
    index: 51,
    fontFamily: "Inter",
    themeColor: "#F1D61B",
  },
  {
    title: "Template52",
    imgUrl: "/images/templates/template52.png",
    index: 52,
    fontFamily: "Lato",
    themeColor: "#304A9F",
  },
  {
    title: "Template53",
    imgUrl: "/images/templates/template53.png",
    index: 53,
    fontFamily: "Montserrat",
    themeColor: "#AC5428",
  },
  {
    title: "Template54",
    imgUrl: "/images/templates/template54.png",
    index: 54,
    fontFamily: "Montserrat",
    themeColor: "#83C3C9",
  },
  {
    title: "Template55",
    imgUrl: "/images/templates/template55.png",
    index: 55,
    fontFamily: "Montserrat",
    themeColor: "#FC9206",
  },
  {
    title: "Template56",
    imgUrl: "/images/templates/template56.png",
    index: 56,
    fontFamily: "Montserrat",
    themeColor: "#56C8E2",
  },
];

export const plans = [
  {
    duration: "1 Day",
    index: 1,
    limit: "One-Time",
    price: "$ 1",
    amount: 1,
    days: 1,
    description: "create your first resume",
    features: [
      "AI Powered Resume Creation",
      "2 Resume Uploads",
      "Unlimited Access to 100+ Resume Templates",
      "Unlimited Access to Skill Assessment",
      "Resume transformation as per job description",
      "2 resume Cloud storage",
    ],
  },
  {
    duration: "7 Days",
    limit: "for More",
    price: "$ 3",
    index: 2,
    amount: 3,
    days: 7,
    description: "for the active job seekers",
    features: [
      "AI Powered Resume Creation",
      "6 Resume Uploads",
      "Unlimited Access to 100+ Resume Templates",
      "Unlimited Access to Skill Assessment",
      "Resume transformation as per job description",
      "6 resume Cloud storage",
    ],
  },
  {
    duration: "30 Days",
    limit: "Ultimate",
    amount: 10,
    price: "$ 10",
    days: 30,
    index: 3,
    description: "create, save, repeat with ease",
    features: [
      "AI Powered Resume Creation",
      "20 Resume Uploads",
      "Unlimited Access to 100+ Resume Templates",
      "Unlimited Access to Skill Assessment",
      "Resume transformation as per job description",
      "20 resume Cloud storage",
    ],
  },
];
