export const ActionTypes = {
    SET_PRODUCTS : 'SET_PRODUCTS',
    SELECTED_PRODUCTS : 'SELECTED_PRODUCTS',
    REMOVE_SELECTED_PRODUCTS : 'REMOVE_SELECTED_PRODUCTS',
    FETCH_PRODUCTS : 'FETCH_PRODUCTS',
    SET_CART : 'SET_CART',
    SET_WISH : 'SET_WISH',
    SET_ADDON : 'SET_ADDON',
    SET_ALL_PRODUCTS : 'SET_ALL_PRODUCTS',
    SET_ADDRESS : 'SET_ADDRESS',
    SET_TAG : 'SET_TAG',
    SET_LOCATION : 'SET_LOCATION',
    SET_CATEGORY : 'SET_CATEGORY',
    SET_ORDER : 'SET_ORDER',
    ADD_TO_CART: 'ADD_TO_CART',
    SET_BANNERS : 'SET_BANNERS',
    SET_WALLET_POINTS : 'SET_WALLET_POINTS',
    
}
export const OrderActionType = {
    SET_ORDER_DATE : 'SET_ORDER_DATE',
   
}
export const CartAction = {
    SET_CART : 'SET_CART',
}
export const UserAction = {
    SET_USER_DATA : 'SET_USER_DATA',
}
export const JobAction = {
    SET_JOB : 'SET_JOB',
}
